version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "gradle"
    directory: "/nm-simple-ktor"
    schedule:
      interval: "daily"

  - package-ecosystem: "gradle"
    directory: "/note-manager-app"
    schedule:
      interval: "daily"
