services:
  red-portal-db:
    build:
      context: ./docker-images/docker-psql/.
    user: postgres
    volumes:
      - ./docker-images/docker-psql/init-scripts:/docker-entrypoint-initdb.d
    expose:
      - 5432
    container_name: red-portal-db
    environment:
      - POSTGRES_USER=yaumatei
      - POSTGRES_PASSWORD=mongkok
      - POSTGRES_MULTIPLE_DATABASES=redportal
    networks:
      - red-portal-network
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "whiskers" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  red-portal-network: