name: note-manager-app-pull-request

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: Set up JDK 18
          uses: actions/setup-java@v2
          with:
            java-version: '18'
            distribution: 'adopt'

        - name: Build and Test
          run: mvn clean install jacoco:prepare-agent package jacoco:report
